// Generated by Wrangler on Tue Mar 05 2024 01:20:44 GMT+0400 (Gulf Standard Time)
// by running `wrangler types`

interface Env {
	SESSION_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	WEBHOOK_BASE: string;
	GEMINI_API_KEY: string;
	DB: D1Database;
}
