name = "gcal-cron"
main = "src/index.ts"
compatibility_date = "2024-02-23"

[[d1_databases]]
binding = "D1"
database_name = "colorcal"
database_id = "b9041cb7-e410-4917-9d35-434d8283f723"

[triggers]
crons = ["* * * * *"]
